# Services, cops, firemen, pilots, ...

file_extension: wav

dirs:
- path: S_FULL_SER/s_f_m_ponsen_01_black_01
- path: S_FULL_SER/s_f_y_airhostess_01_black_full_01
- path: S_FULL_SER/s_f_y_airhostess_01_black_full_02
- path: S_FULL_SER/s_f_y_airhostess_01_white_full_01
- path: S_FULL_SER/s_f_y_airhostess_01_white_full_02
- path: S_FULL_SER/s_f_y_baywatch_01_black_full_01
- path: S_FULL_SER/s_f_y_baywatch_01_black_full_02
- path: S_FULL_SER/s_f_y_baywatch_01_white_full_01
- path: S_FULL_SER/s_f_y_baywatch_01_white_full_02
- path: S_FULL_SER/s_f_y_cop_01_black_full_01
- path: S_FULL_SER/s_f_y_cop_01_black_full_02
- path: S_FULL_SER/s_f_y_cop_01_white_full_01
- path: S_FULL_SER/s_f_y_cop_01_white_full_02
- path: S_FULL_SER/s_f_y_hooker_01_white_full_01
- path: S_FULL_SER/s_f_y_hooker_01_white_full_02
- path: S_FULL_SER/s_f_y_hooker_01_white_full_03
- path: S_FULL_SER/s_f_y_hooker_02_white_full_01
- path: S_FULL_SER/s_f_y_hooker_02_white_full_02
- path: S_FULL_SER/s_f_y_hooker_02_white_full_03
- path: S_FULL_SER/s_f_y_hooker_03_black_full_01
- path: S_FULL_SER/s_f_y_hooker_03_black_full_03
- path: S_FULL_SER/s_f_y_pecker_01_white_01
- path: S_FULL_SER/s_m_m_ammucountry_01_white_01
- path: S_FULL_SER/s_m_m_bouncer_01_black_full_01
- path: S_FULL_SER/s_m_m_bouncer_01_latino_full_01
- path: S_FULL_SER/s_m_m_hairdress_01_black_01
- path: S_FULL_SER/s_m_m_pilot_01_black_full_01
- path: S_FULL_SER/s_m_m_pilot_01_black_full_02
- path: S_FULL_SER/s_m_m_pilot_01_white_full_01
- path: S_FULL_SER/s_m_m_pilot_01_white_full_02
- path: S_FULL_SER/s_m_m_trucker_01_black_full_01
- path: S_FULL_SER/s_m_m_trucker_01_white_full_01
- path: S_FULL_SER/s_m_m_trucker_01_white_full_02
- path: S_FULL_SER/s_m_y_airworker_black_full_01
- path: S_FULL_SER/s_m_y_airworker_black_full_02
- path: S_FULL_SER/s_m_y_airworker_latino_full_01
- path: S_FULL_SER/s_m_y_airworker_latino_full_02
- path: S_FULL_SER/s_m_y_ammucity_01_white_01
- path: S_FULL_SER/s_m_y_ammucity_01_white_mini_01
- path: S_FULL_SER/s_m_y_baywatch_01_black_full_01
- path: S_FULL_SER/s_m_y_baywatch_01_black_full_02
- path: S_FULL_SER/s_m_y_baywatch_01_white_full_01
- path: S_FULL_SER/s_m_y_baywatch_01_white_full_02
- path: S_FULL_SER/s_m_y_cop_01_black_full_01
- path: S_FULL_SER/s_m_y_cop_01_black_full_02
- path: S_FULL_SER/s_m_y_cop_01_white_full_01
- path: S_FULL_SER/s_m_y_cop_01_white_full_02
- path: S_FULL_SER/s_m_y_fireman_01_latino_full_01
- path: S_FULL_SER/s_m_y_fireman_01_latino_full_02
- path: S_FULL_SER/s_m_y_fireman_01_white_full_01
- path: S_FULL_SER/s_m_y_fireman_01_white_full_02
- path: S_FULL_SER/s_m_y_hwaycop_01_black_full_01
- path: S_FULL_SER/s_m_y_hwaycop_01_black_full_02
- path: S_FULL_SER/s_m_y_hwaycop_01_white_full_01
- path: S_FULL_SER/s_m_y_hwaycop_01_white_full_02
- path: S_FULL_SER/s_m_y_ranger_01_latino_full_01
- path: S_FULL_SER/s_m_y_ranger_01_white_full_01
- path: S_FULL_SER/s_m_y_sheriff_01_white_full_01
- path: S_FULL_SER/s_m_y_sheriff_01_white_full_02
- path: S_FULL_SER/s_m_y_swat_01_white_full_01
- path: S_FULL_SER/s_m_y_swat_01_white_full_02
- path: S_FULL_SER/s_m_y_swat_01_white_full_03
- path: S_FULL_SER/s_m_y_swat_01_white_full_04